version: "3.8"

services:

    db:
        container_name: notebook-postgres
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        networks:
          - notebook-network

    redis:
        container_name: notebook-redis
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        networks:
          - notebook-network

networks:
  notebook-network:
    external: true
    driver: bridge
