version: "3.8"

services:
    notebook-server:
        container_name: notebook-server
        restart: unless-stopped
        build: '.'
        ports:
            - "80:80"
        environment:
          - NOTEBOOK_API_HOST=0.0.0.0
          - NOTEBOOK_API_PORT=80
          - NOTEBOOK_DB_HOST=notebook-db.crrfthqir0s7.us-west-1.rds.amazonaws.com
          - NOTEBOOK_DB_USER=notebook
          - NOTEBOOK_DB_PASSWORD=GmApjA8ssTCj8KjMIR8N
          - NOTEBOOK_DB_DATABASE=notebook
          - NOTEBOOK_DB_MAINTENANCE_DATABASE=postgres
          - NOTEBOOK_REDIS_HOST=notebook-redis.774mfm.0001.usw1.cache.amazonaws.com
