const actions = {

    // LOGIN_STARTED : 'LOGIN_STARTED',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    // LOGIN_FAILURE : 'LOGIN_FAILURE',

    GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    UPDATE_NOTE_SUCCESS : 'UPDATE_NOTE_SUCCESS',

    JWT_RECEIVED : 'JWT_RECEIVED',

};
export default actions;
