const actions = {
    // LOAD_NOTE_STARTED : 'LOAD_NOTE_STARTED',
    LOAD_NOTE_SUCCESS : 'LOAD_NOTE_SUCCESS',
    // LOAD_NOTE_FAILURE : 'LOAD_NOTE_FAILURE',

    // LOGIN_STARTED : 'LOGIN_STARTED',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    // LOGIN_FAILURE : 'LOGIN_FAILURE',

    GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',

    // UPDATE_NOTE_STARTED : 'UPDATE_NOTE_STARTED',
    UPDATE_NOTE_SUCCESS : 'UPDATE_NOTE_SUCCESS',
    // UPDATE_NOTE_FAILURE : 'UPDATE_NOTE_FAILURE',

    CREATE_NOTE_STARTED : 'CREATE_NOTE_STARTED',
    // CREATE_NOTE_SUCCESS : 'CREATE_NOTE_SUCCESS',
    // CREATE_NOTE_FAILURE : 'CREATE_NOTE_FAILURE',

    JWT_RECEIVED : 'JWT_RECEIVED',

};
export default actions;
